// pinned.js
// Exact pinned biomarker WHOOP names in required order.

export const PINNED = [
  "ALANINE AMINOTRANSFERASE (ALT)",
  "ALBUMIN/GLOBULIN RATIO",
  "BUN/CREATININE RATIO",
  "CHOLESTEROL / HDL RATIO",
  "FERRITIN",
  "FREE TESTOSTERONE",
  "HEMOGLOBIN A1C (HBA1C)",
  "LDL CHOLESTEROL",
  "NON-HDL CHOLESTEROL",
  "TOTAL CHOLESTEROL",
  "TOTAL IRON-BINDING CAPACITY (TIBC)",
  "TRIGLYCERIDES",
  "VITAMIN D"
];
